services:
  app:
    build: .
    depends_on:
      - tracker_app_database
    stdin_open: true
    tty: true
  tracker_app_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: newAdmin
      POSTGRES_PASSWORD: 5678
      POSTGRES_DB: tracker_app_database
    volumes:
      - tracker-app-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  tracker-app-data:

#Для взаимодействия с приложением через консоль запускать командой docker-compose run app